language: python
python: 3.8

services:
  - docker

env:
  global:
    - CC_TEST_REPORTER_ID=79975336aac47959ad2120a9d5e8de90fc36eacfd0524412edcd0d4b4f7e910f

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install: make

before_install:
  - pip install docker-compose

install:
  - make build

script:
  - make lint
  - make coverage
  - make coverage-xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false